import { MARK_SIGNAL_NAMES } from "@mcp-gcse/shared"
import { z } from "zod/v4"

/**
 * Zod schema for the Gemini structured output when generating annotations
 * for a single question's student answer.
 *
 * The LLM emits SIGNAL annotations only — a physical mark on the script
 * (tick/cross/underline/double_underline/box/circle) with an examiner reason
 * and optional AO tag and comment. `signal` and `reason` are both REQUIRED.
 *
 * TODO: chain annotations (highlighted connective phrases showing reasoning
 * flow) were previously generated by this prompt but were rarely produced,
 * not tied to marker decisions, and a source of empty-output bugs. They were
 * removed 2026-05-17. The persistence layer (`student_paper_annotations.overlay_type
 * = "chain"`) and UI renderer still support them, so a focused chain-generation
 * pass can be added later as its own concern — e.g. a deterministic
 * connective-highlighter or a separate LLM call driven by an explicit user
 * need. Don't reintroduce them into THIS prompt without that separation.
 */
export const AnnotationPlanItemSchema = z.object({
	anchor_start: z
		.number()
		.describe(
			"Start token index as an integer (0-based, inclusive) from the OCR token array",
		),
	anchor_end: z
		.number()
		.describe(
			"End token index as an integer (0-based, inclusive) from the OCR token array",
		),
	sentiment: z
		.enum(["positive", "negative", "neutral"])
		.describe("Sentiment for color coding"),

	signal: z
		.enum(MARK_SIGNAL_NAMES)
		.describe(
			"REQUIRED. The physical signal type drawn on the script (tick, cross, underline, double_underline, box, circle).",
		),
	reason: z
		.string()
		.describe(
			"REQUIRED. Short examiner-style note (max ~10 words) explaining what this mark refers to.",
		),
	label: z
		.string()
		.optional()
		.describe("Optional short label, e.g. '3/4', 'vague'"),

	// ── AO tag fields (optional) ────────────────────────────────────────────
	ao_category: z
		.string()
		.optional()
		.describe("Optional AO skill category e.g. 'AO1', 'AO2', 'AO3'."),
	ao_quality: z
		.enum(["strong", "partial", "incorrect", "valid"])
		.optional()
		.describe(
			"Quality of the AO skill demonstration. Only when ao_category is set.",
		),

	// ── Comment field (optional) ─────────────────────────────────────────────
	comment: z
		.string()
		.optional()
		.describe(
			"Optional margin note. Format: '[diagnosis] → [specific issue]'. Max 8-14 words.",
		),
})

export const AnnotationPlanSchema = z.object({
	annotations: z.array(AnnotationPlanItemSchema),
})

export type AnnotationPlanItem = z.infer<typeof AnnotationPlanItemSchema>
export type AnnotationPlan = z.infer<typeof AnnotationPlanSchema>
