/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnnotationProjectionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "AuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AuthUrl": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "BatchClassifyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "CloudVisionApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CollabAuthz": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "CollabServiceSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ExemplarQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HocuspocusServer": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "Interactions": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MarkSchemePdfQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NeonPostgres": {
      "databaseUrl": string
      "type": "sst.sst.Linkable"
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QuestionPaperQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ScansBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StripeConfig": {
      "foundersCouponId": string
      "foundersSlotLimit": number
      "plans": {
        "pro": {
          "description": string
          "name": string
          "prices": {
            "gbp": {
              "annual": {
                "amount": number
                "id": string
              }
              "monthly": {
                "amount": number
                "id": string
              }
            }
            "usd": {
              "annual": {
                "amount": number
                "id": string
              }
              "monthly": {
                "amount": number
                "id": string
              }
            }
          }
        }
      }
      "productId": string
      "trialPaperCap": number
      "type": "sst.sst.Linkable"
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "secret": string
      "type": "sst.sst.Linkable"
    }
    "StudentPaperGradingDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StudentPaperOcrDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StudentPaperOcrQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StudentPaperQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "VapidPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VapidPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}