/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiGateway": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "AuthTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AuthUrl": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "ExemplarQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ExtractionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GeminiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GithubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GoogleClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Interactions": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MarkSchemePdfQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "NeonPostgres": {
      "databaseUrl": string
      "type": "sst.sst.Linkable"
    }
    "OcrQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "QuestionPaperQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ScansBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StudentPaperOcrQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "StudentPaperQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}