/**
 * Stripe billing infra — the four-product ladder.
 *
 *   PPU set      £10  / $13   one-off,    30 papers (no expiry, in code)
 *   Pro          £24  / $30   monthly,    60 papers/month (capped, expires)
 *                £259 / $324  annual      (kept in infra, not on public page)
 *   Top-up       £6.50/ $8.50 one-off,    15 papers (in-app upsell only)
 *   Limitless    £49  / $62   monthly,    uncapped
 *
 * GBP + USD are the launch currencies; ZAR/AUD added post-launch when those
 * markets justify the tax-registration overhead.
 *
 * Founders' offer: a single Coupon, 40% off, repeating 6 months,
 * max_redemptions 100. Pro only — explicitly NOT applied to Limitless (we
 * want the £49 ceiling to anchor Pro's value). The web-side gate counts
 * active Pro subs and only attaches the coupon while seats remain;
 * Stripe's max_redemptions is the defence-in-depth backstop. Founders pay
 * £14.40 (marketed as £14.50 — 10p drift accepted).
 *
 * The Stripe webhook endpoint + `StripeWebhookSecret` Linkable live in
 * `infra/api.ts` (the URL points at the API Gateway Lambda's
 * `/stripe/webhook` route, so they have to be co-located with `api.url` to
 * avoid an `api.ts` ↔ `billing.ts` import cycle).
 *
 * Source of truth for amounts is the constants below — the marketing
 * pricing page reads them through `Resource.StripeConfig`, so the price
 * shown on the page and the price Stripe charges can never drift.
 */

// ─── Constants ───────────────────────────────────────────────────────────────
// Single source of truth — drives both Coupon.maxRedemptions (Stripe-side
// hard cap) and StripeConfig.foundersSlotLimit (web-app-side gate). Both
// must agree so the UI badge state and the actual coupon-attach decision
// don't diverge.
const FOUNDERS_SLOT_LIMIT = 100

// Founders coupon discount — applied to the Pro monthly price. Both the
// stripe.Coupon definition (server-of-record) and the marketing pricing
// page's displayed founders price read from this single source. Marketing
// rounds £14.40 to £14.50; the 10p drift is acceptable.
const FOUNDERS_DISCOUNT_PERCENT = 40

// PPU + Limitless + Top-up prices. One source of truth for both Stripe Prices
// and the displayed amount on the marketing pricing page — closes the drift
// risk where the page shows one number and Stripe charges another.
const PPU_GBP = 1000 // £10
const PPU_USD = 1300 // $13
const PPU_PAPERS_PER_SET = 30
const LIMITLESS_GBP_MONTHLY = 4900 // £49
const LIMITLESS_USD_MONTHLY = 6200 // $62
// Top-up: in-app upsell when the Pro 60-paper cap bites. Not on the public
// pricing page — only surfaced to subscribers approaching/at their cap.
const TOP_UP_GBP = 650 // £6.50
const TOP_UP_USD = 850 // $8.50
const TOP_UP_PAPERS = 15

// ─── Secrets ─────────────────────────────────────────────────────────────────
// `sst secret set Stripe{Secret,Publishable}Key …` per stage.
// Webhook signing secret is auto-generated by stripe.WebhookEndpoint and
// surfaced via the StripeWebhookSecret Linkable; the WebhookEndpoint itself
// lives in `infra/api.ts` because its URL points at the API Gateway Lambda
// route at `/stripe/webhook` and importing `api` here would create an
// `api.ts` ↔ `billing.ts` cycle.
export const stripeSecretKey = new sst.Secret("StripeSecretKey")
export const stripePublishableKey = new sst.Secret("StripePublishableKey")

// ─── Product ─────────────────────────────────────────────────────────────────
const proProduct = new stripe.Product("ProProduct", {
	name: "DeepMark Pro",
	description: "Examiner-quality marking for GCSE teachers.",
})

// ─── Prices ──────────────────────────────────────────────────────────────────
// Stripe subscription Prices are currency-locked: one Price per currency ×
// interval. Amounts are in the currency's smallest unit (pence / cents).

const proGbpMonthly = new stripe.Price("ProGbpMonthly", {
	product: proProduct.id,
	unitAmount: 2400, // £24.00
	currency: "gbp",
	recurring: { interval: "month", intervalCount: 1 },
})

const proGbpAnnual = new stripe.Price("ProGbpAnnual", {
	product: proProduct.id,
	unitAmount: 25900, // £259.00 — 10.1% off £288
	currency: "gbp",
	recurring: { interval: "year", intervalCount: 1 },
})

const proUsdMonthly = new stripe.Price("ProUsdMonthly", {
	product: proProduct.id,
	unitAmount: 3000, // $30.00
	currency: "usd",
	recurring: { interval: "month", intervalCount: 1 },
})

const proUsdAnnual = new stripe.Price("ProUsdAnnual", {
	product: proProduct.id,
	unitAmount: 32400, // $324.00 — 10% off $360
	currency: "usd",
	recurring: { interval: "year", intervalCount: 1 },
})

// ─── Founders coupon ─────────────────────────────────────────────────────────
const foundersCoupon = new stripe.Coupon("FoundersCoupon", {
	name: `Founders' offer — ${FOUNDERS_DISCOUNT_PERCENT}% off, 6 months`,
	percentOff: FOUNDERS_DISCOUNT_PERCENT,
	duration: "repeating",
	durationInMonths: 6,
	maxRedemptions: FOUNDERS_SLOT_LIMIT,
})

// ─── Limitless tier ──────────────────────────────────────────────────────────
const limitlessProduct = new stripe.Product("LimitlessProduct", {
	name: "DeepMark Limitless",
	description:
		"Uncapped marking — for heavy markers and exam-prep specialists.",
})

const limitlessGbpMonthly = new stripe.Price("LimitlessGbpMonthly", {
	product: limitlessProduct.id,
	unitAmount: LIMITLESS_GBP_MONTHLY,
	currency: "gbp",
	recurring: { interval: "month", intervalCount: 1 },
})

const limitlessUsdMonthly = new stripe.Price("LimitlessUsdMonthly", {
	product: limitlessProduct.id,
	unitAmount: LIMITLESS_USD_MONTHLY,
	currency: "usd",
	recurring: { interval: "month", intervalCount: 1 },
})

// ─── Pay-per-use (PPU) set ───────────────────────────────────────────────────
// One-off purchase, no subscription. Each set is 30 papers scoped to the user
// (cross-exam — exam-scoping is deferred; see build plan).
const ppuProduct = new stripe.Product("PpuProduct", {
	name: "DeepMark — 1 set (30 papers)",
	description: "One question paper, up to 30 student scripts. No subscription.",
})

const ppuGbp = new stripe.Price("PpuGbp", {
	product: ppuProduct.id,
	unitAmount: PPU_GBP,
	currency: "gbp",
})

const ppuUsd = new stripe.Price("PpuUsd", {
	product: ppuProduct.id,
	unitAmount: PPU_USD,
	currency: "usd",
})

// ─── Top-up ──────────────────────────────────────────────────────────────────
// In-app upsell for capped Pro subscribers approaching/at their monthly cap.
// One-off purchase, papers added to the user's cross-exam pool with no expiry.
// NOT surfaced on the public pricing page — see build plan.
const topUpProduct = new stripe.Product("TopUpProduct", {
	name: `DeepMark — top-up (${TOP_UP_PAPERS} papers)`,
	description: `Add ${TOP_UP_PAPERS} papers to your monthly Pro allowance.`,
})

const topUpGbp = new stripe.Price("TopUpGbp", {
	product: topUpProduct.id,
	unitAmount: TOP_UP_GBP,
	currency: "gbp",
})

const topUpUsd = new stripe.Price("TopUpUsd", {
	product: topUpProduct.id,
	unitAmount: TOP_UP_USD,
	currency: "usd",
})

// ─── Webhook endpoint ────────────────────────────────────────────────────────
// Lives in `infra/api.ts` (it points at the API Gateway Lambda's
// `/stripe/webhook` route, so it has to be co-located with `api.url`).

// ─── Linkables exposed to the app ────────────────────────────────────────────
export const stripeConfig = new sst.Linkable("StripeConfig", {
	properties: {
		productId: proProduct.id,
		foundersCouponId: foundersCoupon.id,
		foundersSlotLimit: FOUNDERS_SLOT_LIMIT,
		// Founders discount used by the marketing pricing page to compute the
		// displayed "founders" price from the standard Pro amount. Stays in
		// sync with the stripe.Coupon definition above.
		foundersDiscountPercent: FOUNDERS_DISCOUNT_PERCENT,
		// Trial cap: free users can mark this many papers (counting re-marks +
		// re-scans) before the paywall kicks in. Seeded as a `trial_grant`
		// ledger entry on User creation.
		trialPaperCap: 20,
		// Monthly paper allowance for capped Pro subscribers. Granted as a
		// `subscription_grant` ledger entry on each `invoice.payment_succeeded`;
		// any unused portion is removed by the rollover `period_expiry`. Limitless
		// subscribers ignore this and stay uncapped. Renamed from `proPaperCap`
		// 2026-05-03 — the previous name read as an enforcement cap, but no
		// code enforces it independently; the cap IS the grant size.
		proMonthlyGrantSize: 60,
		plans: {
			pro: {
				name: "Pro",
				description: "Examiner-quality marking for GCSE teachers.",
				prices: {
					gbp: {
						monthly: { id: proGbpMonthly.id, amount: 2400 },
						annual: { id: proGbpAnnual.id, amount: 25900 },
					},
					usd: {
						monthly: { id: proUsdMonthly.id, amount: 3000 },
						annual: { id: proUsdAnnual.id, amount: 32400 },
					},
				},
			},
			limitless: {
				name: "Limitless",
				description:
					"Uncapped marking — for heavy markers and exam-prep specialists.",
				prices: {
					gbp: {
						monthly: {
							id: limitlessGbpMonthly.id,
							amount: LIMITLESS_GBP_MONTHLY,
						},
					},
					usd: {
						monthly: {
							id: limitlessUsdMonthly.id,
							amount: LIMITLESS_USD_MONTHLY,
						},
					},
				},
			},
		},
		// PPU is one-off (no interval), so it sits at the top level rather than
		// inside `plans` (which is for recurring tiers). `papersPerSet` is the
		// fulfilment quantity granted on a successful checkout — read by the
		// webhook handler when writing the `purchase_ppu` ledger row.
		ppu: {
			papersPerSet: PPU_PAPERS_PER_SET,
			gbp: { id: ppuGbp.id, amount: PPU_GBP },
			usd: { id: ppuUsd.id, amount: PPU_USD },
		},
		// Top-up: in-app only, never on the public pricing page. Same fulfilment
		// pattern as PPU — `papersPerPurchase` granted on checkout.completed.
		topUp: {
			papersPerPurchase: TOP_UP_PAPERS,
			gbp: { id: topUpGbp.id, amount: TOP_UP_GBP },
			usd: { id: topUpUsd.id, amount: TOP_UP_USD },
		},
	},
})
