import { domain } from "./config"

/**
 * Stripe billing infra.
 *
 * One Pro tier × two billing intervals (monthly, annual) × two currencies
 * (GBP, USD). Add ZAR/AUD post-launch when those markets justify the
 * tax-registration overhead (Stripe Tax flags it, but we still have to file).
 *
 * Pricing (2026-05-01):
 *   GBP £29/mo, £312/yr (~10% off)
 *   USD $35/mo, $378/yr (~10% off)
 *
 * Founders' offer: ONE Coupon, 50% off, repeating 12 months,
 * max_redemptions 100. Server-side gate counts active Pro subs and only
 * attaches the coupon while seats remain — Stripe's max_redemptions is the
 * defence-in-depth backstop if our count drifts.
 */

// ─── Constants ───────────────────────────────────────────────────────────────
// Single source of truth — drives both Coupon.maxRedemptions (Stripe-side
// hard cap) and StripeConfig.foundersSlotLimit (web-app-side gate). Both
// must agree so the UI badge state and the actual coupon-attach decision
// don't diverge.
const FOUNDERS_SLOT_LIMIT = 100

// ─── Secrets ─────────────────────────────────────────────────────────────────
// `sst secret set Stripe{Secret,Publishable}Key …` per stage.
// Webhook signing secret is auto-generated by stripe.WebhookEndpoint and
// surfaced via the StripeWebhookSecret Linkable below.
export const stripeSecretKey = new sst.Secret("StripeSecretKey")
export const stripePublishableKey = new sst.Secret("StripePublishableKey")

// ─── Product ─────────────────────────────────────────────────────────────────
const proProduct = new stripe.Product("ProProduct", {
	name: "DeepMark Pro",
	description: "Examiner-quality marking for GCSE teachers.",
})

// ─── Prices ──────────────────────────────────────────────────────────────────
// Stripe subscription Prices are currency-locked: one Price per currency ×
// interval. Amounts are in the currency's smallest unit (pence / cents).

const proGbpMonthly = new stripe.Price("ProGbpMonthly", {
	product: proProduct.id,
	unitAmount: 2900, // £29.00
	currency: "gbp",
	recurring: { interval: "month", intervalCount: 1 },
})

const proGbpAnnual = new stripe.Price("ProGbpAnnual", {
	product: proProduct.id,
	unitAmount: 31200, // £312.00 — 10.3% off £348
	currency: "gbp",
	recurring: { interval: "year", intervalCount: 1 },
})

const proUsdMonthly = new stripe.Price("ProUsdMonthly", {
	product: proProduct.id,
	unitAmount: 3500, // $35.00
	currency: "usd",
	recurring: { interval: "month", intervalCount: 1 },
})

const proUsdAnnual = new stripe.Price("ProUsdAnnual", {
	product: proProduct.id,
	unitAmount: 37800, // $378.00 — 10% off $420
	currency: "usd",
	recurring: { interval: "year", intervalCount: 1 },
})

// ─── Founders coupon ─────────────────────────────────────────────────────────
const foundersCoupon = new stripe.Coupon("FoundersCoupon", {
	name: "Founders' offer — 50% off year one",
	percentOff: 50,
	duration: "repeating",
	durationInMonths: 12,
	maxRedemptions: FOUNDERS_SLOT_LIMIT,
})

// ─── Webhook endpoint ────────────────────────────────────────────────────────
// One endpoint per stage, addressed at the deployed marketing/app domain.
// Local `sst dev` works because dev mode tunnels traffic from the deployed
// CloudFront URL down to localhost — no Stripe CLI forwarding needed.
const stripeWebhook = new stripe.WebhookEndpoint("StripeWebhook", {
	url: `https://${domain}/api/stripe/webhook`,
	enabledEvents: [
		"checkout.session.completed",
		"customer.subscription.created",
		"customer.subscription.updated",
		"customer.subscription.deleted",
		"invoice.payment_succeeded",
		"invoice.payment_failed",
	],
})

// ─── Linkables exposed to the app ────────────────────────────────────────────
export const stripeConfig = new sst.Linkable("StripeConfig", {
	properties: {
		productId: proProduct.id,
		foundersCouponId: foundersCoupon.id,
		foundersSlotLimit: FOUNDERS_SLOT_LIMIT,
		// Trial cap: free users can mark this many papers (counting re-marks +
		// re-scans) before the paywall kicks in.
		trialPaperCap: 20,
		plans: {
			pro: {
				name: "Pro",
				description: "Examiner-quality marking for GCSE teachers.",
				prices: {
					gbp: {
						monthly: { id: proGbpMonthly.id, amount: 2900 },
						annual: { id: proGbpAnnual.id, amount: 31200 },
					},
					usd: {
						monthly: { id: proUsdMonthly.id, amount: 3500 },
						annual: { id: proUsdAnnual.id, amount: 37800 },
					},
				},
			},
		},
	},
})

export const stripeWebhookSecret = new sst.Linkable("StripeWebhookSecret", {
	properties: { secret: stripeWebhook.secret },
})
