"use client"

import { AnnotationHitTarget } from "@/components/BoundingBoxViewer/annotation-hit-target"
import { ChainOverlay } from "@/components/BoundingBoxViewer/chain-overlay"
import { GradingAnnotationOverlay } from "@/components/BoundingBoxViewer/grading-annotation-overlay"
import { MarkOverlay } from "@/components/BoundingBoxViewer/mark-overlay"
import { TokenOverlay } from "@/components/BoundingBoxViewer/token-overlay"
import { HandwritingAnalysisPanel } from "@/components/HandwritingAnalysisPanel"
import {
	type GradingAnnotation,
	TOKEN_COLOR,
	annotationColor,
} from "@/lib/marking/bounding-box"
import type {
	HandwritingAnalysis,
	PageToken,
	StudentPaperAnnotation,
} from "@/lib/marking/types"
import { cn } from "@/lib/utils"
import { Minus, Plus, RotateCcw } from "lucide-react"
import { useState } from "react"
import { TransformComponent, TransformWrapper } from "react-zoom-pan-pinch"

export type { GradingAnnotation }

// ─── TransformWrapper config ──────────────────────────────────────────────────

const TRANSFORM_MIN_SCALE = 0.3
const TRANSFORM_MAX_SCALE = 8
const TRANSFORM_WHEEL = { step: 0.08, activationKeys: ["Control", "Meta"] }
const TRANSFORM_PINCH = { step: 5 }
const TRANSFORM_DOUBLE_CLICK = { mode: "reset" as const }

// ─── Main viewer ──────────────────────────────────────────────────────────────

type Props = {
	imageUrl: string
	analysis: HandwritingAnalysis
	/** Word-level tokens from Cloud Vision — rendered as interactive overlays. */
	tokens?: PageToken[]
	className?: string
	/** When false, transcript and observations are omitted (shown elsewhere). */
	showAnalysisText?: boolean
	/** Controls word-token highlight visibility. Defaults to false. */
	showHighlights?: boolean
	/** Grading annotations to overlay on the image — one per question answer region. */
	gradingAnnotations?: GradingAnnotation[]
	/** Called when a grading annotation region is clicked, with the question number. */
	onAnnotationClick?: (questionNumber: string) => void
	/** When true, shows debug labels on fallback-sourced regions. */
	debugMode?: boolean
	/** Annotation overlays generated by the enrichment processor. */
	annotations?: StudentPaperAnnotation[]
	/** Controls mark overlay visibility. */
	showMarks?: boolean
	/** Controls chain indicator highlight visibility. */
	showChains?: boolean
	/** Called when an enrichment annotation is clicked, with the question ID. */
	onEnrichmentAnnotationClick?: (questionId: string) => void
}

export function BoundingBoxViewer({
	imageUrl,
	analysis,
	tokens = [],
	className,
	showAnalysisText = true,
	showHighlights = false,
	gradingAnnotations,
	onAnnotationClick,
	debugMode = false,
	annotations = [],
	showMarks = false,
	showChains = false,
	onEnrichmentAnnotationClick,
}: Props) {
	const [imageDims, setImageDims] = useState<{ w: number; h: number } | null>(
		null,
	)

	const handleImageLoad = (e: React.SyntheticEvent<HTMLImageElement>) => {
		setImageDims({
			w: e.currentTarget.naturalWidth,
			h: e.currentTarget.naturalHeight,
		})
	}

	const viewBox = imageDims
		? `0 0 ${imageDims.w} ${imageDims.h}`
		: "0 0 1000 1000"
	const scaleX = (imageDims?.w ?? 1000) / 1000
	const scaleY = (imageDims?.h ?? 1000) / 1000

	const hasAnnotations =
		gradingAnnotations !== undefined && gradingAnnotations.length > 0

	return (
		<div className={cn("space-y-2", className)}>
			<TransformWrapper
				minScale={TRANSFORM_MIN_SCALE}
				maxScale={TRANSFORM_MAX_SCALE}
				wheel={TRANSFORM_WHEEL}
				pinch={TRANSFORM_PINCH}
				doubleClick={TRANSFORM_DOUBLE_CLICK}
				limitToBounds={false}
			>
				{({ zoomIn, zoomOut, resetTransform }) => (
					<>
						{/* Zoom controls */}
						<div className="flex items-center justify-end gap-1 pb-1">
							<button
								type="button"
								onClick={() => zoomOut(0.5)}
								className="flex h-7 w-7 items-center justify-center rounded border bg-background text-muted-foreground transition-colors hover:bg-muted"
								aria-label="Zoom out"
							>
								<Minus className="h-3.5 w-3.5" />
							</button>
							<button
								type="button"
								onClick={() => resetTransform()}
								className="flex h-7 w-7 items-center justify-center rounded border bg-background text-muted-foreground transition-colors hover:bg-muted"
								aria-label="Reset zoom"
								title="Reset zoom (or double-click the image)"
							>
								<RotateCcw className="h-3.5 w-3.5" />
							</button>
							<button
								type="button"
								onClick={() => zoomIn(0.5)}
								className="flex h-7 w-7 items-center justify-center rounded border bg-background text-muted-foreground transition-colors hover:bg-muted"
								aria-label="Zoom in"
							>
								<Plus className="h-3.5 w-3.5" />
							</button>
						</div>

						<TransformComponent
							wrapperStyle={{
								width: "100%",
								overflow: "hidden",
								borderRadius: "0.5rem",
							}}
							contentStyle={{ width: "100%" }}
						>
							<div className="relative w-full overflow-visible rounded-lg border bg-muted cursor-grab active:cursor-grabbing">
								{/* eslint-disable-next-line @next/next/no-img-element -- presigned S3 URL */}
								<img
									src={imageUrl}
									alt="Uploaded handwritten page"
									className="block w-full rounded-lg"
									onLoad={handleImageLoad}
									draggable={false}
								/>

								{imageDims && (
									<>
										{/* Grading annotation bands */}
										{hasAnnotations && (
											<svg
												aria-hidden="true"
												viewBox={viewBox}
												preserveAspectRatio="none"
												className="absolute inset-0 h-full w-full"
												style={{ pointerEvents: "none" }}
											>
												{gradingAnnotations.map((ann, i) => {
													const [yMin, xMin, yMax, xMax] = ann.box
													if (yMax === 0 && xMax === 0) return null
													const color = annotationColor(
														ann.awardedScore,
														ann.maxScore,
													)
													return (
														// biome-ignore lint/suspicious/noArrayIndexKey: static annotation overlay
														<g key={i}>
															<rect
																x={xMin * scaleX}
																y={yMin * scaleY}
																width={(xMax - xMin) * scaleX}
																height={(yMax - yMin) * scaleY}
																fill={color}
																fillOpacity={0.1}
																stroke={color}
																strokeWidth={2}
																strokeOpacity={0.5}
															/>
															{debugMode &&
																ann.source === "gemini_fallback" && (
																	<>
																		<rect
																			x={xMin * scaleX}
																			y={yMin * scaleY}
																			width={120}
																			height={18}
																			fill="rgb(31 41 55)"
																			fillOpacity={0.85}
																		/>
																		<text
																			x={xMin * scaleX + 6}
																			y={yMin * scaleY + 12}
																			fill="white"
																			fontSize="10"
																			fontWeight="600"
																		>
																			gemini_fallback
																		</text>
																	</>
																)}
														</g>
													)
												})}
											</svg>
										)}

										{/* Chain indicator highlight layer (background) */}
										{showChains && annotations.length > 0 && (
											<svg
												aria-hidden="true"
												viewBox={viewBox}
												preserveAspectRatio="none"
												className="absolute inset-0 h-full w-full"
												style={{ pointerEvents: "none" }}
											>
												{annotations
													.filter(
														(
															a,
														): a is Extract<
															StudentPaperAnnotation,
															{ overlay_type: "chain" }
														> => a.overlay_type === "chain",
													)
													.map((a) => (
														<ChainOverlay
															key={a.id}
															annotation={a}
															scaleX={scaleX}
															scaleY={scaleY}
														/>
													))}
											</svg>
										)}

										{/* Signal annotation visual layer (no pointer events) */}
										{showMarks && annotations.length > 0 && (
											<svg
												aria-hidden="true"
												viewBox={viewBox}
												preserveAspectRatio="none"
												className="absolute inset-0 h-full w-full"
												style={{ pointerEvents: "none" }}
											>
												{annotations
													.filter(
														(
															a,
														): a is Extract<
															StudentPaperAnnotation,
															{ overlay_type: "annotation" }
														> => a.overlay_type === "annotation",
													)
													.map((a) => (
														<MarkOverlay
															key={a.id}
															annotation={a}
															scaleX={scaleX}
															scaleY={scaleY}
														/>
													))}
											</svg>
										)}

										{/* Unified annotation interaction layer */}
										{(showMarks || showChains) &&
											annotations
												.filter(
													(a) =>
														a.overlay_type === "annotation" ||
														a.overlay_type === "chain",
												)
												.map((a) => (
													<AnnotationHitTarget
														key={a.id}
														annotation={a}
														onClick={() =>
															onEnrichmentAnnotationClick?.(a.question_id)
														}
													/>
												))}

										{/* Word-level highlight layer */}
										{showHighlights && tokens.length > 0 && (
											<svg
												aria-hidden="true"
												viewBox={viewBox}
												preserveAspectRatio="none"
												className="absolute inset-0 h-full w-full"
												style={{
													pointerEvents: "none",
													mixBlendMode: "multiply",
												}}
											>
												{tokens.map((t, i) => {
													const [yMin, xMin, yMax, xMax] = t.bbox
													return (
														<rect
															// biome-ignore lint/suspicious/noArrayIndexKey: static token overlay
															key={i}
															x={xMin * scaleX}
															y={yMin * scaleY}
															width={(xMax - xMin) * scaleX}
															height={(yMax - yMin) * scaleY}
															fill={TOKEN_COLOR}
															fillOpacity={0.25}
															stroke="none"
														/>
													)
												})}
											</svg>
										)}

										{/* Grading annotation click targets */}
										{hasAnnotations &&
											gradingAnnotations.map((ann, i) => (
												<GradingAnnotationOverlay
													// biome-ignore lint/suspicious/noArrayIndexKey: static annotation list
													key={i}
													annotation={ann}
													onAnnotationClick={onAnnotationClick}
												/>
											))}

										{/* Word-level token popovers */}
										{showHighlights &&
											tokens.map((t, i) => (
												<TokenOverlay key={t.id} token={t} index={i} />
											))}
									</>
								)}
							</div>
						</TransformComponent>
					</>
				)}
			</TransformWrapper>

			{showAnalysisText ? (
				<HandwritingAnalysisPanel analysis={analysis} />
			) : null}
		</div>
	)
}
